# Generated by Django 2.2.12 on 2020-10-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField()),
                ('original_name', models.CharField(max_length=200)),
                ('filename', models.CharField(default='', max_length=200)),
                ('thumb_frame', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTagName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTagList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.VideoContent')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.VideoTagName')),
            ],
        ),
    ]
